import type { Listing } from '../src/lib/types';

/**
 * Verified starter dataset for Home Reach.
 *
 * Every entry below is a REAL Essex County housing authority or affordable
 * property with a public source. Per the site's promise, nothing here is
 * fabricated. Where a field could not be verified from a public source it is
 * left conservative:
 *   - `waitlist_open` defaults to false so the site never falsely advertises
 *     an open waitlist; flip to true only when confirmed against the source.
 *   - `rent` is null ("contact for rent") unless a public figure is known.
 *   - `bedroom_types` is left empty when unspecified (matches any bedroom filter).
 *   - `ami_bands` reflect the program's typical income tiers (HCV/public housing
 *     serve ~30–50% AMI; LIHTC family units ~50–60%; senior LIHTC ~30–60%),
 *     not a claim about a specific unit.
 *
 * Grow this list (or replace it with a live scraper in ingest.ts) over time.
 * Sources are recorded per row; last_verified reflects when the row was checked.
 */

export type SeedListing = Omit<Listing, 'id'>;

const VERIFIED = '2026-07-09';
// Second research pass: individually cross-checked (not bulk-extracted) against
// 2+ independent sources per listing after a bulk PDF extraction produced one
// confirmed error (a senior community in the wrong town, wrongly typed as
// affordable). Anything that couldn't be independently confirmed was dropped
// rather than included on a single unverified mention.
const VERIFIED_2 = '2026-07-12';

export const SEED_LISTINGS: SeedListing[] = [
  {
    name: 'Housing Choice Voucher Program (Section 8)',
    address: '57 Sussex Ave',
    city: 'Newark',
    program_type: 'Section 8 / HCV',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: 'https://www.newarkha.org/Status-Check',
    phone: '973-273-6206',
    priority_groups: [],
    accessible: false,
    source: 'Newark Housing Authority',
    source_url: 'https://www.newarkha.org/Programs-Services/Housing-Choice-Voucher-Program-Section-8',
    last_verified: VERIFIED,
  },
  {
    name: 'Public Housing Program',
    address: '57 Sussex Ave',
    city: 'Newark',
    program_type: 'Public Housing',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: 'https://www.newarkha.org/Status-Check',
    phone: '973-273-6206',
    priority_groups: [],
    accessible: false,
    source: 'Newark Housing Authority',
    source_url: 'https://www.newarkha.org/',
    last_verified: VERIFIED,
  },
  {
    name: 'Spruce St. Senior Residences',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC / Senior',
    ami_bands: [30, 50, 60],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: ['senior'],
    accessible: true,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/spruce-st-sr-residences-23880-lihtc',
    last_verified: VERIFIED,
  },
  {
    name: 'Lincoln Avenue Apartments',
    address: null,
    city: 'Orange',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/orange/lincoln-avenue-apartments-24068-lihtc',
    last_verified: VERIFIED,
  },
  {
    name: 'South Essex Court',
    address: null,
    city: 'Orange',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/orange-city/south-essex-court-22621-lihtc',
    last_verified: VERIFIED,
  },
  {
    name: 'Tri-Corner Homes',
    address: null,
    city: 'Orange',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/orange/litc06902-tri-corner-homes-22883-lihtc',
    last_verified: VERIFIED,
  },
  {
    name: 'Montclair Inn Senior Housing',
    address: null,
    city: 'Montclair',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: ['senior'],
    accessible: true,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/cty/nj-essex',
    last_verified: VERIFIED,
  },
  {
    name: 'Housing Choice Voucher & Public Housing',
    address: null,
    city: 'East Orange',
    program_type: 'Section 8 / Public Housing',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Housing Authority of the City of East Orange',
    source_url: 'https://www.affordablehousing.com/housing-authority-essex-county-nj/',
    last_verified: VERIFIED,
  },
  {
    name: 'Housing Authority of the City of Orange Township',
    address: null,
    city: 'Orange',
    program_type: 'Section 8 / Public Housing',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'AffordableHousing.com',
    source_url: 'https://www.affordablehousing.com/housing-authority-essex-county-nj/',
    last_verified: VERIFIED,
  },
  {
    name: 'Irvington Housing Authority',
    address: null,
    city: 'Irvington',
    program_type: 'Section 8 / Public Housing',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'AffordableHousing.com',
    source_url: 'https://www.affordablehousing.com/housing-authority-essex-county-nj/',
    last_verified: VERIFIED,
  },

  // --- Second pass: individually verified, 4 new municipalities ---

  {
    name: 'Corinthian Homes, Phase II',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: ['2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/corinthian-homes-phase-ii-23735-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Richardson Lofts',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/richardson-lofts-23828-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Villa Esperanza',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: ['Studio', '1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/villa-esperanza-56166-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Genesis Newark',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/genesis-newark-22528-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Prince Hall - Et Bowser Complex',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: ['Studio', '1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/prince-hall-et-bowser-complex-22969-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Baxter Park South',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/baxter-park-south-23954-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Hayes Homes/West Kinney (B)',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/hayes-homeswest-kinney-b-53429-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Cottage Place',
    address: '643 Martin Luther King Jr Blvd',
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-297-0001',
    priority_groups: [],
    accessible: false,
    source: 'Cottage Place (official site)',
    source_url: 'https://www.cottageplaceliving.com/',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Lincoln Court II',
    address: null,
    city: 'Orange',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex-county/orange/lincoln-court-ii-24066-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Corinthian Towers',
    address: '67 South Munn Ave',
    city: 'East Orange',
    program_type: 'Section 8 (Project-Based)',
    ami_bands: [50],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-643-8588',
    priority_groups: [],
    accessible: true,
    source: 'AffordableHousingOnline.com',
    source_url: 'https://affordablehousingonline.com/housing-search/New-Jersey/East-Orange/Corinthian-Towers/10019587',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Edward & Lois Gray Apartments',
    address: '712 15th Ave',
    city: 'Irvington',
    program_type: 'Section 8 (Project-Based)',
    ami_bands: [50],
    bedroom_types: ['1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-375-9551',
    priority_groups: ['senior', 'disability'],
    accessible: true,
    source: 'Region Nine Housing Corporation',
    source_url: 'https://rnhousing.org/properties/edward-and-lois-gray-apartments/',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Franklin Manor',
    address: '608 Mill St',
    city: 'Belleville',
    program_type: 'HMFA / Senior',
    ami_bands: [30, 50, 60],
    bedroom_types: ['1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-302-4430',
    priority_groups: ['senior'],
    accessible: true,
    source: 'Franklin Manor (official site)',
    source_url: 'https://www.franklinmanorbellevillenj.com/',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Kinder Towers',
    address: '400 Hoover Ave',
    city: 'Bloomfield',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-748-0982',
    priority_groups: ['senior'],
    accessible: true,
    source: 'National Church Residences',
    source_url: 'https://senioraffordable.nationalchurchresidences.org/apartments/nj/bloomfield/kinder-towers/default',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Maplewood Senior Citizens',
    address: '564 Irvington Ave',
    city: 'Maplewood',
    program_type: 'Section 8 (Project-Based) / Senior',
    ami_bands: [50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-763-4578',
    priority_groups: ['senior'],
    accessible: false,
    source: 'AffordableHousingOnline.com',
    source_url:
      'https://affordablehousingonline.com/housing-search/New-Jersey/Maplewood/Maplewood-Senior-Citizens/10019639',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Two South Willow',
    address: '2 S Willow St',
    city: 'Montclair',
    program_type: 'Inclusionary Set-Aside (20 of 200 units)',
    ami_bands: [50, 80],
    bedroom_types: ['Studio', '1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Jersey Digs / Two South Willow (official site)',
    source_url: 'https://twosouthwillow.com/',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Brookplace',
    address: null,
    city: 'Fairfield',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Piazza & Associates',
    source_url: 'https://www.piazzanj.com/property/brookplace/',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Magnolia Lane',
    address: null,
    city: 'Fairfield',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: ['2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Piazza & Associates',
    source_url: 'https://www.piazzanj.com/property/magnolia-lane/',
    last_verified: VERIFIED_2,
  },
];
