import type { Listing } from '../src/lib/types';

/**
 * Verified starter dataset for Home Reach.
 *
 * Every entry below is a REAL Essex County housing authority or affordable
 * property with a public source. Per the site's promise, nothing here is
 * fabricated. Where a field could not be verified from a public source it is
 * left conservative:
 *   - `waitlist_open` defaults to false so the site never falsely advertises
 *     an open waitlist; flip to true only when confirmed against the source.
 *   - `rent` is null ("contact for rent") unless a public figure is known.
 *   - `bedroom_types` is left empty when unspecified (matches any bedroom filter).
 *   - `ami_bands` reflect the program's typical income tiers (HCV/public housing
 *     serve ~30–50% AMI; LIHTC family units ~50–60%; senior LIHTC ~30–60%),
 *     not a claim about a specific unit.
 *
 * Grow this list (or replace it with a live scraper in ingest.ts) over time.
 * Sources are recorded per row; last_verified reflects when the row was checked.
 */

export type SeedListing = Omit<Listing, 'id'>;

const VERIFIED = '2026-07-09';
// Second research pass: individually cross-checked (not bulk-extracted) against
// 2+ independent sources per listing after a bulk PDF extraction produced one
// confirmed error (a senior community in the wrong town, wrongly typed as
// affordable). Anything that couldn't be independently confirmed was dropped
// rather than included on a single unverified mention.
const VERIFIED_2 = '2026-07-12';
// Third pass: targeted per-town searches for previously-uncovered municipalities.
// Entries kept have a concrete address and/or phone from a reputable housing
// directory (publichousing.com, lowincomehousing.us) or the town's own
// government site. One ambiguous town attribution (a property returned for
// both Livingston and Caldwell) was resolved using the more specific,
// address-anchored source. Two candidates were dropped outright: one likely
// private-pay elder care rather than income-restricted rental housing, and
// one with no address or other verifiable specifics.
const VERIFIED_3 = '2026-07-14';
// Fourth pass: parallel research fan-out across 4 geographic clusters (Newark;
// East Orange/Orange/Irvington; Montclair/Bloomfield/Belleville/Nutley/
// Maplewood/South Orange/Fairfield; remaining western towns), each held to
// the same bar — concrete address/phone from a reputable directory or the
// property's/town's own site, ambiguous town attributions resolved or
// dropped, private-pay senior care distinguished from income-restricted
// rental housing. For-sale/resale ownership programs were excluded to match
// the site's rental-application/waitlist model.
const VERIFIED_4 = '2026-07-14';

export const SEED_LISTINGS: SeedListing[] = [
  {
    name: 'Housing Choice Voucher Program (Section 8)',
    address: '57 Sussex Ave',
    city: 'Newark',
    program_type: 'Section 8 / HCV',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: 'https://www.newarkha.org/Status-Check',
    phone: '973-273-6206',
    priority_groups: [],
    accessible: false,
    source: 'Newark Housing Authority',
    source_url: 'https://www.newarkha.org/Programs-Services/Housing-Choice-Voucher-Program-Section-8',
    last_verified: VERIFIED,
  },
  {
    name: 'Public Housing Program',
    address: '57 Sussex Ave',
    city: 'Newark',
    program_type: 'Public Housing',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: 'https://www.newarkha.org/Status-Check',
    phone: '973-273-6206',
    priority_groups: [],
    accessible: false,
    source: 'Newark Housing Authority',
    source_url: 'https://www.newarkha.org/',
    last_verified: VERIFIED,
  },
  {
    name: 'Spruce St. Senior Residences',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC / Senior',
    ami_bands: [30, 50, 60],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: ['senior'],
    accessible: true,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/spruce-st-sr-residences-23880-lihtc',
    last_verified: VERIFIED,
  },
  {
    name: 'Lincoln Avenue Apartments',
    address: null,
    city: 'Orange',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/orange/lincoln-avenue-apartments-24068-lihtc',
    last_verified: VERIFIED,
  },
  {
    name: 'South Essex Court',
    address: null,
    city: 'Orange',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/orange-city/south-essex-court-22621-lihtc',
    last_verified: VERIFIED,
  },
  {
    name: 'Tri-Corner Homes',
    address: null,
    city: 'Orange',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/orange/litc06902-tri-corner-homes-22883-lihtc',
    last_verified: VERIFIED,
  },
  {
    name: 'Montclair Inn Senior Housing',
    address: null,
    city: 'Montclair',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: ['senior'],
    accessible: true,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/cty/nj-essex',
    last_verified: VERIFIED,
  },
  {
    name: 'Housing Choice Voucher & Public Housing',
    address: null,
    city: 'East Orange',
    program_type: 'Section 8 / Public Housing',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Housing Authority of the City of East Orange',
    source_url: 'https://www.affordablehousing.com/housing-authority-essex-county-nj/',
    last_verified: VERIFIED,
  },
  {
    name: 'Housing Authority of the City of Orange Township',
    address: null,
    city: 'Orange',
    program_type: 'Section 8 / Public Housing',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'AffordableHousing.com',
    source_url: 'https://www.affordablehousing.com/housing-authority-essex-county-nj/',
    last_verified: VERIFIED,
  },
  {
    name: 'Irvington Housing Authority',
    address: null,
    city: 'Irvington',
    program_type: 'Section 8 / Public Housing',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'AffordableHousing.com',
    source_url: 'https://www.affordablehousing.com/housing-authority-essex-county-nj/',
    last_verified: VERIFIED,
  },

  // --- Second pass: individually verified, 4 new municipalities ---

  {
    name: 'Corinthian Homes, Phase II',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: ['2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/corinthian-homes-phase-ii-23735-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Richardson Lofts',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/richardson-lofts-23828-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Villa Esperanza',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: ['Studio', '1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/villa-esperanza-56166-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Genesis Newark',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/genesis-newark-22528-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Prince Hall - Et Bowser Complex',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: ['Studio', '1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/prince-hall-et-bowser-complex-22969-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Baxter Park South',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/baxter-park-south-23954-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Hayes Homes/West Kinney (B)',
    address: null,
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url:
      'https://affordablehousinghub.org/housing/new-jersey/essex-county/newark/hayes-homeswest-kinney-b-53429-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Cottage Place',
    address: '643 Martin Luther King Jr Blvd',
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-297-0001',
    priority_groups: [],
    accessible: false,
    source: 'Cottage Place (official site)',
    source_url: 'https://www.cottageplaceliving.com/',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Lincoln Court II',
    address: null,
    city: 'Orange',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex-county/orange/lincoln-court-ii-24066-lihtc',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Corinthian Towers',
    address: '67 South Munn Ave',
    city: 'East Orange',
    program_type: 'Section 8 (Project-Based)',
    ami_bands: [50],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-643-8588',
    priority_groups: [],
    accessible: true,
    source: 'AffordableHousingOnline.com',
    source_url: 'https://affordablehousingonline.com/housing-search/New-Jersey/East-Orange/Corinthian-Towers/10019587',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Edward & Lois Gray Apartments',
    address: '712 15th Ave',
    city: 'Irvington',
    program_type: 'Section 8 (Project-Based)',
    ami_bands: [50],
    bedroom_types: ['1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-375-9551',
    priority_groups: ['senior', 'disability'],
    accessible: true,
    source: 'Region Nine Housing Corporation',
    source_url: 'https://rnhousing.org/properties/edward-and-lois-gray-apartments/',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Franklin Manor',
    address: '608 Mill St',
    city: 'Belleville',
    program_type: 'HMFA / Senior',
    ami_bands: [30, 50, 60],
    bedroom_types: ['1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-302-4430',
    priority_groups: ['senior'],
    accessible: true,
    source: 'Franklin Manor (official site)',
    source_url: 'https://www.franklinmanorbellevillenj.com/',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Kinder Towers',
    address: '400 Hoover Ave',
    city: 'Bloomfield',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-748-0982',
    priority_groups: ['senior'],
    accessible: true,
    source: 'National Church Residences',
    source_url: 'https://senioraffordable.nationalchurchresidences.org/apartments/nj/bloomfield/kinder-towers/default',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Maplewood Senior Citizens',
    address: '564 Irvington Ave',
    city: 'Maplewood',
    program_type: 'Section 8 (Project-Based) / Senior',
    ami_bands: [50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-763-4578',
    priority_groups: ['senior'],
    accessible: false,
    source: 'AffordableHousingOnline.com',
    source_url:
      'https://affordablehousingonline.com/housing-search/New-Jersey/Maplewood/Maplewood-Senior-Citizens/10019639',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Two South Willow',
    address: '2 S Willow St',
    city: 'Montclair',
    program_type: 'Inclusionary Set-Aside (20 of 200 units)',
    ami_bands: [50, 80],
    bedroom_types: ['Studio', '1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Jersey Digs / Two South Willow (official site)',
    source_url: 'https://twosouthwillow.com/',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Brookplace',
    address: null,
    city: 'Fairfield',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Piazza & Associates',
    source_url: 'https://www.piazzanj.com/property/brookplace/',
    last_verified: VERIFIED_2,
  },
  {
    name: 'Magnolia Lane',
    address: null,
    city: 'Fairfield',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: ['2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Piazza & Associates',
    source_url: 'https://www.piazzanj.com/property/magnolia-lane/',
    last_verified: VERIFIED_2,
  },

  // --- Third pass: 8 previously-uncovered municipalities ---

  {
    name: 'Woodland Valley',
    address: '115 Woodland Ave',
    city: 'West Orange',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-736-6802',
    priority_groups: ['senior'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/nj/west_orange.html',
    last_verified: VERIFIED_3,
  },
  {
    name: 'West Orange Senior Citizens Housing',
    address: '10 Gaston St',
    city: 'West Orange',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-736-3130',
    priority_groups: ['senior'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/nj/west_orange.html',
    last_verified: VERIFIED_3,
  },
  {
    name: 'James A. Degnan House',
    address: null,
    city: 'West Orange',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: ['senior'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/nj/west_orange.html',
    last_verified: VERIFIED_3,
  },
  {
    name: 'Al Gomer Residence',
    address: null,
    city: 'South Orange',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50, 60],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: ['senior'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/nj/south_orange.html',
    last_verified: VERIFIED_3,
  },
  {
    name: 'Nutley Parkside Apartments',
    address: null,
    city: 'Nutley',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50],
    bedroom_types: ['1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: ['senior'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07110-2756-nutley_parkside_apartments',
    last_verified: VERIFIED_3,
  },
  {
    name: 'Nutley Senior Manor',
    address: null,
    city: 'Nutley',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: ['senior'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/nj/nutley.html',
    last_verified: VERIFIED_3,
  },
  {
    name: 'ParkVue at Livingston',
    address: '660 South Orange Ave',
    city: 'Livingston',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Livingston Township (official)',
    source_url: 'https://www.livingstonnj.org/387/Affordable-Housing',
    last_verified: VERIFIED_3,
  },
  {
    name: 'Marian Manor Apartments',
    address: '7 Ashland St',
    city: 'Caldwell',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-226-3433',
    priority_groups: ['senior'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/nj/caldwell.html',
    last_verified: VERIFIED_3,
  },
  {
    name: 'West Caldwell Group Home',
    address: '7 Essex Pl',
    city: 'West Caldwell',
    program_type: 'HUD Subsidized / Disability',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-763-8018',
    priority_groups: ['disability'],
    accessible: true,
    source: 'West Caldwell Township (official)',
    source_url: 'https://www.westcaldwell.com/pages/affordable-housing',
    last_verified: VERIFIED_3,
  },
  {
    name: 'Verona Senior Citizens Apartments',
    address: '100 Hillwood Ter',
    city: 'Verona',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-239-3131',
    priority_groups: ['senior'],
    accessible: true,
    source: 'PublicHousing.com',
    source_url: 'https://www.publichousing.com/details/verona_senior_citizens_apartments',
    last_verified: VERIFIED_3,
  },
  {
    name: 'Cedar Grove Senior Citizens Housing',
    address: '100 Cedar Ridge Dr',
    city: 'Cedar Grove',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-857-2290',
    priority_groups: ['senior'],
    accessible: false,
    source: 'PublicHousing.com',
    source_url: 'https://www.publichousing.com/details/cedar_grove_senior_citizen',
    last_verified: VERIFIED_3,
  },

  // --- Fourth pass: 77 entries across 4 parallel research clusters ---

  {
    name: 'Wesley Towers',
    address: '444 Mt Prospect Ave',
    city: 'Newark',
    program_type: 'Section 202 / HUD Project-Based Rental Assistance',
    ami_bands: [50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-484-4441',
    priority_groups: ['senior', 'disability'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07104_wesley-towers',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Court Towers Senior Apartments',
    address: '1 Court St',
    city: 'Newark',
    program_type: 'RAD Section 8 Project-Based Rental Assistance',
    ami_bands: [50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-623-0766',
    priority_groups: ['senior'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07102_court-towers',
    last_verified: VERIFIED_4,
  },
  {
    name: 'The Willows at Symphony Hall',
    address: '395 Halsey St',
    city: 'Newark',
    program_type: 'LIHTC / HUD HOME',
    ami_bands: [50, 60],
    bedroom_types: ['1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-844-6220',
    priority_groups: [],
    accessible: false,
    source: 'PublicHousing.com',
    source_url: 'https://www.publichousing.com/details/nj_the-willows-at-symphony-hall',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Pilgrim Baptist Village I & II',
    address: '446 Bergen St',
    city: 'Newark',
    program_type: 'Section 8 Project-Based Rental Assistance / LIHTC preservation',
    ami_bands: [50],
    bedroom_types: ['1BR', '2BR', '3BR', '4BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-242-4748',
    priority_groups: ['senior'],
    accessible: true,
    source: 'AffordableHousingOnline.com',
    source_url: 'https://affordablehousingonline.com/housing-search/New-Jersey/Newark/Pilgrim-Baptist-Village-I-and-II/10019669',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Georgia King Village',
    address: '250 Georgia King Vlg',
    city: 'Newark',
    program_type: 'RAD Section 8 Project-Based Rental Assistance / LIHTC 40/60',
    ami_bands: [50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-622-6828',
    priority_groups: [],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07107_georgia-king-village',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Garden Spires',
    address: '175-199 1st St',
    city: 'Newark',
    program_type: 'Section 8 Project-Based Rental Assistance / LIHTC',
    ami_bands: [50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-481-9200',
    priority_groups: [],
    accessible: false,
    source: 'AffordableHousingOnline.com',
    source_url: 'https://affordablehousingonline.com/housing-search/New-Jersey/Newark/Garden-Spires-Urban-Renewal/10109702',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Lincoln Towers',
    address: '63-91 Lincoln St',
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: ['1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-900-5463',
    priority_groups: ['senior'],
    accessible: false,
    source: 'AffordableHousingOnline.com',
    source_url: 'https://affordablehousingonline.com/housing-search/New-Jersey/Newark/Lincoln-Towers/10107183',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Center City Apartments',
    address: '25 Johnson Ave',
    city: 'Newark',
    program_type: 'Subsidized (HUD multifamily)',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-282-1100',
    priority_groups: [],
    accessible: false,
    source: 'HudHouses.us',
    source_url: 'https://www.hudhouses.us/city/nj-newark',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Amity Village #7',
    address: '410-536 South 19th St',
    city: 'Newark',
    program_type: 'Subsidized (HUD multifamily)',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-680-8489',
    priority_groups: [],
    accessible: false,
    source: 'HudHouses.us',
    source_url: 'https://www.hudhouses.us/city/nj-newark',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Somerset Homes',
    address: '142-172 Somerset St',
    city: 'Newark',
    program_type: 'Subsidized (HUD multifamily)',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-643-8588',
    priority_groups: [],
    accessible: false,
    source: 'HudHouses.us',
    source_url: 'https://www.hudhouses.us/city/nj-newark',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Essex Plaza I',
    address: '1060 Broad St',
    city: 'Newark',
    program_type: 'Subsidized (HUD multifamily)',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-643-8588',
    priority_groups: [],
    accessible: false,
    source: 'HudHouses.us',
    source_url: 'https://www.hudhouses.us/city/nj-newark',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Hampton Valley Apartments',
    address: '106-136 Elizabeth Ave',
    city: 'Newark',
    program_type: 'LIHTC / Insured-Subsidized',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-624-8948',
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex/newark',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Grace West Manor Apartments',
    address: '301 Irvine Turner Blvd',
    city: 'Newark',
    program_type: 'Insured-Subsidized (HUD multifamily)',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'HudHouses.us',
    source_url: 'https://www.hudhouses.us/city/nj-newark',
    last_verified: VERIFIED_4,
  },
  {
    name: 'The Associates',
    address: '180 South Orange Ave',
    city: 'Newark',
    program_type: 'Section 8 Project-Based (New Community Corporation)',
    ami_bands: [50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-623-6872',
    priority_groups: ['senior', 'disability'],
    accessible: false,
    source: 'New Community Corporation (official site)',
    source_url: 'https://newcommunity.org/housing-opportunities/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Commons Senior',
    address: '140 South Orange Ave',
    city: 'Newark',
    program_type: 'Section 8 Project-Based (New Community Corporation)',
    ami_bands: [50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-623-6870',
    priority_groups: ['senior'],
    accessible: false,
    source: 'New Community Corporation (official site)',
    source_url: 'https://newcommunity.org/housing-opportunities/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Gardens Senior',
    address: '265 Morris Ave',
    city: 'Newark',
    program_type: 'Section 8 Project-Based (New Community Corporation)',
    ami_bands: [50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-623-6945',
    priority_groups: ['senior'],
    accessible: false,
    source: 'New Community Corporation (official site)',
    source_url: 'https://newcommunity.org/housing-opportunities/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Roseville Senior',
    address: '1 South 8th St',
    city: 'Newark',
    program_type: 'Section 8 Project-Based (New Community Corporation)',
    ami_bands: [50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-482-5766',
    priority_groups: ['senior'],
    accessible: false,
    source: 'New Community Corporation (official site)',
    source_url: 'https://newcommunity.org/housing-opportunities/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Commons Family',
    address: '220 Bruce St',
    city: 'Newark',
    program_type: 'Family townhouses (New Community Corporation)',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-623-6870',
    priority_groups: [],
    accessible: false,
    source: 'New Community Corporation (official site)',
    source_url: 'https://newcommunity.org/housing-opportunities/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Estates',
    address: '14th Avenue',
    city: 'Newark',
    program_type: 'Family townhouses (New Community Corporation)',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-623-7280',
    priority_groups: [],
    accessible: false,
    source: 'New Community Corporation (official site)',
    source_url: 'https://newcommunity.org/housing-opportunities/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Sussex',
    address: '78 North 6th St',
    city: 'Newark',
    program_type: 'Family apartments (New Community Corporation)',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-623-7280',
    priority_groups: [],
    accessible: false,
    source: 'New Community Corporation (official site)',
    source_url: 'https://newcommunity.org/housing-opportunities/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Douglas Homes',
    address: '15 Hill St',
    city: 'Newark',
    program_type: 'Section 8 Project-Based, senior (New Community Corporation)',
    ami_bands: [50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-623-6871',
    priority_groups: ['senior'],
    accessible: false,
    source: 'New Community Corporation (official site)',
    source_url: 'https://newcommunity.org/housing-opportunities/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Weequahic Park Apartments III',
    address: '1 Grumman Ave',
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex/newark',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Aspen Riverpark Apartments',
    address: '17 Oxford St',
    city: 'Newark',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex/newark',
    last_verified: VERIFIED_4,
  },
  {
    name: 'St. James AME Tower Apartments',
    address: '440 Washington St',
    city: 'Newark',
    program_type: 'LIHTC / Subsidized',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'HudHouses.us',
    source_url: 'https://www.hudhouses.us/city/nj-newark',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Betty Shabazz Village',
    address: '45A Lincoln St',
    city: 'Newark',
    program_type: 'Public Housing (Newark Housing Authority)',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex/newark',
    last_verified: VERIFIED_4,
  },
  {
    name: 'James C. White Manor',
    address: '516-518 Bergen St',
    city: 'Newark',
    program_type: 'Public Housing (Newark Housing Authority)',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex/newark',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Felix Fuld',
    address: '186 Muhammad Ali Ave',
    city: 'Newark',
    program_type: 'Public Housing (Newark Housing Authority)',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex/newark',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Norman Towers',
    address: '500 N Walnut St',
    city: 'East Orange',
    program_type: 'Section 8 Project-Based Rental Assistance (RAD), senior affordable',
    ami_bands: [50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: ['senior'],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://search.affordablehousinghub.org/nj/essex/east-orange/section-8-apartments-details/9747/norman-towers',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Doddtown Plaza',
    address: '9 Long St',
    city: 'East Orange',
    program_type: 'HUD Subsidized (Section 8 Project-Based)',
    ami_bands: [50],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-673-1248',
    priority_groups: [],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07017-1215-doddtown_plaza',
    last_verified: VERIFIED_4,
  },
  {
    name: 'The Pavilion (220 Prospect Holdings)',
    address: '220 Prospect St',
    city: 'East Orange',
    program_type: 'RAD Section 8 Project-Based Rental Assistance',
    ami_bands: [50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-677-3332',
    priority_groups: ['senior'],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://search.affordablehousinghub.org/nj/essex/east-orange/section-8-apartments-details/10347/220-prospect-holdings',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Bailey-Holt Tower',
    address: '25 S Grove St',
    city: 'East Orange',
    program_type: 'Section 8 Project-Based Rental Assistance',
    ami_bands: [50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-673-5070',
    priority_groups: ['senior'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07018-4167-bailey-holt_towers',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Coppergate House',
    address: '780 Springdale Ave',
    city: 'East Orange',
    program_type: 'Section 8 Project-Based Rental Assistance',
    ami_bands: [50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-678-4900',
    priority_groups: ['senior'],
    accessible: false,
    source: 'PublicHousing.com',
    source_url: 'https://www.publichousing.com/details/coppergate_house',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Arlington House',
    address: '55-57 S Munn Ave',
    city: 'East Orange',
    program_type: 'Project-Based Rental Assistance (HUD), senior housing',
    ami_bands: [50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-678-3866',
    priority_groups: ['senior'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07012-3687-arlington_house',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Heritage House',
    address: '50 S Munn Ave',
    city: 'East Orange',
    program_type: 'LIHTC 40/60 Set-Aside + Section 8 Project-Based Rental Assistance',
    ami_bands: [50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-677-9111',
    priority_groups: ['senior', 'disability'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07018-3617-heritage_house',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Vista Village',
    address: '70 S Burnet St',
    city: 'East Orange',
    program_type: 'Public Housing (East Orange Housing Authority)',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-766-8896',
    priority_groups: ['senior', 'disability'],
    accessible: false,
    source: 'East Orange Housing Authority',
    source_url: 'https://www.eoha.org/public-housing',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Concord Towers',
    address: '210 N Grove St',
    city: 'East Orange',
    program_type: 'Public Housing (East Orange Housing Authority)',
    ami_bands: [30, 50],
    bedroom_types: ['1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-766-8896',
    priority_groups: ['senior', 'disability'],
    accessible: false,
    source: 'East Orange Housing Authority',
    source_url: 'https://www.eoha.org/public-housing',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Oakwood Towers',
    address: '400-402 Oakwood Ave',
    city: 'Orange',
    program_type: 'HUD Section 202/8, Project-Based Section 8',
    ami_bands: [50],
    bedroom_types: ['1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-678-2189',
    priority_groups: ['senior', 'disability'],
    accessible: true,
    source: 'PublicHousing.com',
    source_url: 'https://www.lowincomehousing.us/det/07050-3279-oakwood_towers',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Salem Towers',
    address: '98 High St',
    city: 'Orange',
    program_type: 'RAD Section 8 Project-Based Rental Assistance',
    ami_bands: [50],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-678-5768',
    priority_groups: ['senior', 'disability'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07050-1637-salem_towers',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Mount Carmel Towers',
    address: '268-275 Oakwood Ave',
    city: 'Orange',
    program_type: 'HUD Subsidized, age-restricted senior housing',
    ami_bands: [30, 50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-678-6662',
    priority_groups: ['senior'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07050-3250-mount_carmel_towers',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Washington Manor',
    address: '340 Thomas Blvd',
    city: 'Orange',
    program_type: 'Public Housing (Orange Housing Authority)',
    ami_bands: [30, 50],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-675-1250',
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://search.affordablehousinghub.org/nj/essex/orange/public-housing-details/washington-manor',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Washington Dodd Apartments',
    address: '587 Carroll St',
    city: 'Orange',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-674-0303',
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://search.affordablehousinghub.org/nj/essex/orange/low-income-housing-details/29342/washington-dodd-apartments',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Orange Park Apartments',
    address: '300 Oakwood Ave',
    city: 'Orange',
    program_type: 'Project-Based Section 8 (HUD)',
    ami_bands: [50],
    bedroom_types: ['1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-672-4949',
    priority_groups: ['senior'],
    accessible: false,
    source: 'PublicHousing.com',
    source_url: 'https://www.lowincomehousing.us/det/07050-3278-orange_park_apartments',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Hilltop Apartments (Senior)',
    address: '280 Park Place, Building 2',
    city: 'Irvington',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-358-9777',
    priority_groups: ['senior'],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex-county/irvington/hilltop-apartments-23499-lihtc',
    last_verified: VERIFIED_4,
  },
  {
    name: '280 Park Place Apartments',
    address: '280 Park Place',
    city: 'Irvington',
    program_type: 'LIHTC 40/60 Set-Aside',
    ami_bands: [50, 60],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-358-6363',
    priority_groups: [],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/280-park-place-apartments',
    last_verified: VERIFIED_4,
  },
  {
    name: '722 Chancellor Apartments',
    address: '722 Chancellor Ave',
    city: 'Irvington',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '844-299-3563',
    priority_groups: ['disability'],
    accessible: false,
    source: 'Affordable Housing Online',
    source_url: 'https://affordablehousingonline.com/housing-search/New-Jersey/Irvington/722-Chancellor-Apartments/10109036',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Irvington Gardens',
    address: '278 Orange Ave',
    city: 'Irvington',
    program_type: 'Section 8 Project-Based Rental Assistance',
    ami_bands: [50],
    bedroom_types: ['1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-399-3989',
    priority_groups: [],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07111-2140-irvington_gardens',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Berkeley Terrace',
    address: '10 Berkeley Terrace',
    city: 'Irvington',
    program_type: 'Section 8 Project-Based Rental Assistance, VASH',
    ami_bands: [50],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '732-383-7715',
    priority_groups: ['veteran'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07111-3703-berkeley_terrace',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Matthew G. Carter Apartments',
    address: '20-80 Glenridge Ave',
    city: 'Montclair',
    program_type: 'Section 8 Project-Based Rental Assistance',
    ami_bands: [50],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-746-9165',
    priority_groups: [],
    accessible: false,
    source: 'USDOH.org',
    source_url: 'https://www.usdoh.org/property/nj_Glen_matthew-g-carter-apartments',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Union Gardens',
    address: '50 Greenwood Ave',
    city: 'Montclair',
    program_type: 'Affordable Set-Aside',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-746-9055',
    priority_groups: [],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07042-3618-union_gardens',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Grafton Avenue Apartments',
    address: '273 Valley Rd',
    city: 'Montclair',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Affordable Housing Hub',
    source_url: 'https://affordablehousinghub.org/housing/new-jersey/essex/montclair',
    last_verified: VERIFIED_4,
  },
  {
    name: 'PineRidge of Montclair',
    address: '60 Glenridge Avenue',
    city: 'Montclair',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50, 60],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-746-0003',
    priority_groups: ['senior'],
    accessible: false,
    source: 'United Methodist Communities',
    source_url: 'https://umcommunities.org/pineridge-of-montclair/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'First Montclair House',
    address: '56 Walnut St',
    city: 'Montclair',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50, 60],
    bedroom_types: ['Studio', '1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-746-0895',
    priority_groups: ['senior'],
    accessible: false,
    source: 'USDOH.org',
    source_url: 'https://www.usdoh.org/property/nj_56_first-montclair-house-senior-apartments',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Felicity Towers',
    address: '100 Llewellyn Ave',
    city: 'Bloomfield',
    program_type: 'HUD Subsidized / Senior',
    ami_bands: [30, 50, 60],
    bedroom_types: ['Studio', '1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-743-2060',
    priority_groups: ['senior'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/nj/bloomfield.html',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Heritage Village at Bloomfield',
    address: '390 Franklin Street',
    city: 'Bloomfield',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: ['1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: ['senior'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/heritage-village-at-bloomfield',
    last_verified: VERIFIED_4,
  },
  {
    name: 'CPEWH Group Home 1',
    address: '42 State St',
    city: 'Bloomfield',
    program_type: 'Section 811 Supportive Housing for Persons with Disabilities',
    ami_bands: [30],
    bedroom_types: ['1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-751-0200',
    priority_groups: ['disability'],
    accessible: true,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07003-2529-cpewh_group_home_1',
    last_verified: VERIFIED_4,
  },
  {
    name: 'CPEWH Group Home 2',
    address: '31 Cuozzo St',
    city: 'Belleville',
    program_type: 'Section 811 Supportive Housing for Persons with Disabilities',
    ami_bands: [30],
    bedroom_types: ['1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: ['disability'],
    accessible: true,
    source: 'HUDHouses.us',
    source_url: 'https://www.hudhouses.us/city/nj-belleville',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Project Live XII Consumer Home',
    address: '82 King Street',
    city: 'Nutley',
    program_type: 'HUD Subsidized / Disability group home',
    ami_bands: [30, 50, 60],
    bedroom_types: ['3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-481-1211',
    priority_groups: ['disability'],
    accessible: false,
    source: 'PublicHousing.com',
    source_url: 'https://www.publichousing.com/details/project_live_xii_consumer_home',
    last_verified: VERIFIED_4,
  },
  {
    name: '95 Tiffany Place',
    address: '93-95 Tiffany Place',
    city: 'Maplewood',
    program_type: 'Affordable Set-Aside (National Housing Trust Fund)',
    ami_bands: [50, 80],
    bedroom_types: ['2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Patch.com',
    source_url: 'https://patch.com/new-jersey/maplewood/maplewood-approves-pilot-affordable-housing-project',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Avalon Maplewood',
    address: '200 Boyden Ave',
    city: 'Maplewood',
    program_type: 'Affordable Set-Aside (inclusionary zoning)',
    ami_bands: [50, 80],
    bedroom_types: ['Studio', '1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '908-258-6477',
    priority_groups: [],
    accessible: false,
    source: 'Maplewood Township affordable housing list',
    source_url: 'https://patch.com/new-jersey/maplewood/maplewoods-affordable-housing-list-open-applications',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Maplewood Crossing',
    address: '92-98 Burnett Ave',
    city: 'Maplewood',
    program_type: 'Affordable Set-Aside (inclusionary zoning)',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Maplewood Township affordable housing list',
    source_url: 'https://patch.com/new-jersey/maplewood/maplewoods-affordable-housing-list-open-applications',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Station House at Maplewood',
    address: '125 Dunnell Road',
    city: 'Maplewood',
    program_type: 'Affordable Set-Aside (inclusionary zoning)',
    ami_bands: [50, 80],
    bedroom_types: ['Studio', '1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Maplewood Township affordable housing list',
    source_url: 'https://patch.com/new-jersey/maplewood/maplewoods-affordable-housing-list-open-applications',
    last_verified: VERIFIED_4,
  },
  {
    name: '1611 Springfield Avenue',
    address: '1611 Springfield Ave',
    city: 'Maplewood',
    program_type: 'Affordable Set-Aside',
    ami_bands: [50, 80],
    bedroom_types: ['1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Maplewood Township affordable housing list',
    source_url: 'https://www.apartments.com/1611-springfield-ave-maplewood-nj/08xs8h1/',
    last_verified: VERIFIED_4,
  },
  {
    name: '255 Tuscan',
    address: '255 Tuscan Rd',
    city: 'Maplewood',
    program_type: 'Affordable Set-Aside (inclusionary zoning)',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'Maplewood Township affordable housing list',
    source_url: 'https://patch.com/new-jersey/maplewood/maplewoods-affordable-housing-list-open-applications',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Third & Valley',
    address: '153 Valley Street',
    city: 'South Orange',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: ['Studio', '1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '609-786-1100',
    priority_groups: ['veteran'],
    accessible: false,
    source: 'Piazza & Associates',
    source_url: 'https://www.piazzanj.com/property/third-valley/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Vose + Taylor',
    address: '52 Taylor Place',
    city: 'South Orange',
    program_type: 'Affordable Set-Aside (inclusionary housing)',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'South Orange Village (official)',
    source_url: 'https://www.southorange.org/847/Vose-Taylor',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Mosaic at 8 Second Street',
    address: '8 Second Street',
    city: 'South Orange',
    program_type: 'Affordable Set-Aside (COAH)',
    ami_bands: [50, 80],
    bedroom_types: [],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: null,
    priority_groups: [],
    accessible: false,
    source: 'South Orange Village (official)',
    source_url: 'https://www.southorange.org/CivicAlerts.aspx?AID=2476',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Woodcrest at Fairfield',
    address: '29 Greenbrook Road #4',
    city: 'Fairfield',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-364-9690',
    priority_groups: ['senior'],
    accessible: false,
    source: 'Piazza & Associates',
    source_url: 'https://www.piazzanj.com/property/woodcrest-at-fairfield/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'The Kingsley',
    address: '2000 Murray Court',
    city: 'Fairfield',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-227-0003',
    priority_groups: [],
    accessible: false,
    source: 'Piazza & Associates',
    source_url: 'https://www.piazzanj.com/property/the-kingsley/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'The View at Fairfield',
    address: '264 Passaic Avenue',
    city: 'Fairfield',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-834-9500',
    priority_groups: [],
    accessible: false,
    source: 'Piazza & Associates',
    source_url: 'https://www.piazzanj.com/property/the-view-at-fairfield/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'The Gardens at Roseland',
    address: '1 Spango Court',
    city: 'Roseland',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '609-786-1100',
    priority_groups: [],
    accessible: false,
    source: 'Piazza & Associates',
    source_url: 'https://www.piazzanj.com/property/the-gardens-at-roseland/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'The Upton Short Hills',
    address: '1 Fineran Way, Short Hills',
    city: 'Millburn',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '609-786-1100',
    priority_groups: [],
    accessible: false,
    source: 'Piazza & Associates',
    source_url: 'https://www.piazzanj.com/property/the-upton-at-short-hills/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Landmark Lofts',
    address: '80 Roseland Ave',
    city: 'Caldwell',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '609-786-1100',
    priority_groups: [],
    accessible: false,
    source: 'Piazza & Associates',
    source_url: 'https://www.piazzanj.com/property/landmark-lofts/',
    last_verified: VERIFIED_4,
  },
  {
    name: '459 Bloomfield Ave (The Central at Caldwell)',
    address: '459 Bloomfield Ave',
    city: 'Caldwell',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '609-786-1100',
    priority_groups: [],
    accessible: false,
    source: 'Piazza & Associates',
    source_url: 'https://www.piazzanj.com/property/459-bloomfield-ave/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'The Hillside Club',
    address: '1000 Murray Court',
    city: 'Livingston',
    program_type: 'Affordable Set-Aside (Fair Share)',
    ami_bands: [50, 80],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '609-786-1100',
    priority_groups: [],
    accessible: false,
    source: 'Piazza & Associates',
    source_url: 'https://www.piazzanj.com/property/the-hillside-club/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Project Live VIII',
    address: '70 Osborne Street',
    city: 'Glen Ridge',
    program_type: 'Section 811 Supportive Housing for Persons with Disabilities',
    ami_bands: [30],
    bedroom_types: ['1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-481-1211',
    priority_groups: ['disability'],
    accessible: false,
    source: 'Affordable Housing Online',
    source_url: 'https://affordablehousingonline.com/housing-search/New-Jersey/Glen-Ridge/Project-Live-VIII/10020191',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Verona Flats',
    address: '1 Linn Drive',
    city: 'Verona',
    program_type: 'LIHTC',
    ami_bands: [50, 60],
    bedroom_types: ['1BR', '2BR', '3BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '862-203-7424',
    priority_groups: ['disability'],
    accessible: true,
    source: 'Conifer Realty LLC (official site)',
    source_url: 'https://coniferllc.com/properties/verona-flats/',
    last_verified: VERIFIED_4,
  },
  {
    name: 'Project Live X',
    address: '26 Mt. Prospect Ave',
    city: 'Verona',
    program_type: 'HUD Subsidized / Group Home for Persons with Psychiatric Disabilities',
    ami_bands: [30],
    bedroom_types: ['1BR'],
    rent: null,
    waitlist_open: false,
    application_link: null,
    phone: '973-481-1211',
    priority_groups: ['disability'],
    accessible: false,
    source: 'LowIncomeHousing.us',
    source_url: 'https://www.lowincomehousing.us/det/07044-project_live_x',
    last_verified: VERIFIED_4,
  },
];
